[project]
name = "vortex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.20.0",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.14.0",
    "pyqtwebengine>=5.15.7",
    "pyserial>=3.5",
]

[tool.uv]
required-environments = ["sys_platform == 'win32'"]
